### ISSUE TITLE
s3 object byte range support

### ISSUE THREAD

**Issue by tooptoop4** [hongquan/Defity#1]
boto3 library has s3 get_object that accepts a byte range (to avoid downloading a whole file but just download selected byte range). if my file is 100mb, can this library do some byte range seek to only download the s3 object partially (ie the first 1000 bytes) and then determine file type?

**Comment by hongquan** [comment]
@tooptoop4 You can download first 1000 bytes yourself then pass to [`defity.from_bytes`](https://defity.readthedocs.io/en/latest/api-ref.html#defity.from_bytes).

Defity tries to avoid doing I/O, to give you freedom of choosing any I/O client you want, sync or async, authenticating by environment variable or credentials file.

**Comment by tooptoop4** [comment]
@hongquan is there a list of file types you can detect? for example Avro or parquet

**Comment by hongquan** [comment]
@tooptoop4 There is no fixed list, because it bases on the FreeDesktop's [Shared MIME-info Database](https://specifications.freedesktop.org/shared-mime-info-spec/shared-mime-info-spec-latest.html) saved in the machine (_/usr/share/mime_). The default data doesn't have _application/avro_, so this file type is not supported by Defity. But if you can find some description of this type, compliant with the shared-mime-info spec and install to your machine, Defity will support.
